version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    # Install dependencies for Read the Docs
    - requirements: docs/requirements.txt
    # Install PowNet package
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

